# Generated by Django 6.0.5 on 2026-05-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('condition', models.CharField(choices=[('new', '全新'), ('almost_new', '九成新'), ('good', '良好'), ('fair', '一般')], default='good', max_length=20, verbose_name='新旧程度')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='商品主图')),
                ('status', models.SmallIntegerField(choices=[(0, '待售'), (1, '交易中'), (2, '已售出'), (3, '已下架')], default=0, verbose_name='商品状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='goods.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '二手商品',
                'verbose_name_plural': '二手商品',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
